import { useParams } from "react-router-dom";
import QRPreview from "../components/QRPreview";
import StatusBadge from "../components/ui/StatusBadge";
import { useTraceability } from "../hooks/useApi";

const STAGE_COLORS: Record<string, string> = {
  GRN_RECEIVED: "bg-sky-500",
  WAREHOUSE: "bg-slate-500",
  MATERIAL_ISSUED: "bg-amber-500",
  PRODUCTION_CONSUMED: "bg-purple-500",
  FINISHED_GOODS_CREATED: "bg-emerald-500",
  DISPATCHED: "bg-industrial-800",
};

export default function TraceabilityPage() {
  const { traceId } = useParams<{ traceId: string }>();
  const { data, isLoading, error } = useTraceability(traceId);

  if (isLoading) {
    return <div className="text-industrial-400 text-sm">Loading traceability record...</div>;
  }

  if (error || !data) {
    return (
      <div className="card p-6 text-center">
        <p className="text-red-500 font-medium">No batch found for Trace ID {traceId}</p>
        <p className="text-sm text-industrial-500 mt-1">
          Double check the code, or scan a valid QR generated by this system.
        </p>
      </div>
    );
  }

  const { batch, qrCode, timeline, upstreamRawMaterials, downstreamFinishedGoods } = data;

  return (
    <div className="space-y-6">
      <div className="flex flex-col lg:flex-row gap-6">
        <div className="card p-5 flex-1 space-y-3">
          <div className="flex items-center gap-3 flex-wrap">
            <h2 className="text-xl font-bold text-industrial-900 font-mono">{batch.traceId}</h2>
            <StatusBadge status={batch.batchType} />
            <StatusBadge status={batch.status} />
          </div>
          <p className="text-industrial-700 font-medium">{batch.productName} ({batch.productSku})</p>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4 pt-2 text-sm">
            <Field label="Batch Number" value={batch.batchNumber} />
            <Field label="Lot Number" value={batch.lotNumber ?? "-"} />
            <Field label="Packaging" value={batch.packagingType ?? "-"} />
            <Field label="Quantity" value={`${batch.quantity} ${batch.uom}`} />
            <Field label="Remaining" value={`${batch.remainingQuantity} ${batch.uom}`} />
            <Field label="Warehouse" value={batch.warehouseLocation ?? "-"} />
            <Field label="Manufacturing Date" value={batch.manufacturingDate ?? "-"} />
            <Field label="Expiry Date" value={batch.expiryDate ?? "-"} />
          </div>
        </div>
        {qrCode && (
          <div className="card p-5 w-full lg:w-64 shrink-0">
            <QRPreview traceId={batch.traceId} />
          </div>
        )}
      </div>

      <div className="card p-5">
        <h3 className="font-semibold text-industrial-800 mb-4">Traceability Timeline</h3>
        {timeline.length === 0 ? (
          <p className="text-sm text-industrial-400">No movement recorded yet for this batch.</p>
        ) : (
          <ol className="relative border-l-2 border-industrial-200 ml-2">
            {timeline.map((event, idx) => (
              <li key={idx} className="mb-6 ml-6">
                <span
                  className={`absolute -left-[9px] flex h-4 w-4 items-center justify-center rounded-full ring-4 ring-white ${
                    STAGE_COLORS[event.stage] ?? "bg-industrial-400"
                  }`}
                />
                <div className="flex items-center gap-2 flex-wrap">
                  <h4 className="text-sm font-semibold text-industrial-800">{event.title}</h4>
                  <span className="text-xs text-industrial-400">
                    {new Date(event.timestamp).toLocaleString()}
                  </span>
                </div>
                <p className="text-sm text-industrial-600 mt-0.5">{event.description}</p>
              </li>
            ))}
          </ol>
        )}
      </div>

      {upstreamRawMaterials.length > 0 && (
        <div className="card p-5">
          <h3 className="font-semibold text-industrial-800 mb-3">
            Upstream Raw Materials ({upstreamRawMaterials.length})
          </h3>
          <SimpleTable rows={upstreamRawMaterials} />
        </div>
      )}

      {downstreamFinishedGoods.length > 0 && (
        <div className="card p-5">
          <h3 className="font-semibold text-industrial-800 mb-3">
            Downstream Finished Goods ({downstreamFinishedGoods.length})
          </h3>
          <SimpleTable rows={downstreamFinishedGoods} />
        </div>
      )}
    </div>
  );
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <div className="text-[11px] font-semibold uppercase tracking-wide text-industrial-400">{label}</div>
      <div className="text-industrial-800">{value}</div>
    </div>
  );
}

function SimpleTable({ rows }: { rows: Array<Record<string, unknown>> }) {
  if (rows.length === 0) return null;
  const columns = Object.keys(rows[0]);
  return (
    <div className="overflow-x-auto">
      <table className="w-full text-sm">
        <thead>
          <tr className="text-left text-industrial-500 text-xs uppercase border-b border-industrial-100">
            {columns.map((c) => (
              <th key={c} className="py-2 pr-4 whitespace-nowrap">
                {c.replace(/([A-Z])/g, " $1")}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, i) => (
            <tr key={i} className="border-b border-industrial-50">
              {columns.map((c) => (
                <td key={c} className="py-2 pr-4 whitespace-nowrap">
                  {String(row[c] ?? "-")}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
